weights: yolov5s.pt
cfg: ''
data: "D:\\CCU \u5B78\u6821(Class)\u4E8B\u52D9\\CCU\u4E0A\u8AB2\\Robotic arm vision\\\
  Final_project\\yolov5_new_version\\data\\car.yaml"
hyp: data\hyps\hyp.scratch-low.yaml
epochs: 50
batch_size: 5
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp22
